### ISSUE TITLE
「Alert: 新增失敗：檔案上傳大小不可超過 5MB」should raise exceptions

### ISSUE THREAD

**Issue by MrOrz** [littleq0903/ntpc_social_robot#6]
Should throw here
https://github.com/littleq0903/ntpc_social_robot/blob/master/app.py#L138

**Comment by littleq0903** [comment]
The problem should be at here: https://github.com/littleq0903/ntpc_social_robot/blob/master/app.py#L227

if in the debugging mode, it will raise an exception here before updating the filename, this is probably what happened in today's testing, because we turn on the DEBUG flag.

and BTW @MrOrz did you change back the DEBUG var to `False` after issues got solved?

**Comment by MrOrz** [comment]
The copy inside administrator still has `DEBUG=True` (I totally forgot to turn it off lol), but I think the copy currently in use does not.

AFAIR in the message printed in console (that is the title of this issue), the word "alert" exists, followed by a single line that reads "failed" . I think L138 is more suspicious and relevant to this issue.

**Comment by littleq0903** [comment]
I was saying that because https://github.com/littleq0903/ntpc_social_robot/blob/master/app.py#L229 is actually how I update the filename. You could find it out this line captures exceptions and update the filename if captured.

in L138, the `print "failed"` is a redundant statement actually.

**Comment by littleq0903** [comment]
BTW, good to know the DEBUG is set on only administrator.

Oh, you're probably right, L138 still has to raise an exception because it got an alert message.

Just do it. You're awesome!

**Comment by littleq0903** [comment]
did you test it?

**Comment by MrOrz** [comment]
Dunno how to test QQ

Colin Su (LittleQ) notifications@github.com 於 2015年6月26日週五 上午10:50 寫道：
